common/models/DealGallery.php
<?php

namespace common\models;

use yii\imagine\Image;
use Yii;

/**
 * This is the model class for table "{{%deal_gallery}}".
 *
 * @property integer $id
 * @property integer $deal_id
 * @property integer $deal_option_id
 * @property integer $sort_order
 * @property string $name
 * @property string $size
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property Deal $deal
 */
class DealGallery extends \common\components\GenxBaseModel
{

    public $imageFile;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%deal_gallery}}';
    }

    /**
     * @inheritdoc
     */
    public function rules($rules = array())
    {
        return parent::rules([
                    [['deal_id', 'name'], 'required'],
                    [['sort_order'], 'default', 'value' => 20],
                    [['deal_id', 'deal_option_id', 'sort_order'], 'integer'],
                    [['imageFile'], 'file', 'skipOnEmpty' => !($this->isNewRecord), 'extensions' => 'png, jpg'],
                    [['size', 'name', 'description'], 'string', 'max' => 255],
                    [['deal_id'], 'exist', 'skipOnError' => true, 'targetClass' => Deal::className(), 'targetAttribute' => ['deal_id' => 'id']],
                    [['deal_option_id'], 'exist', 'skipOnError' => true, 'targetClass' => DealOption::className(), 'targetAttribute' => ['deal_option_id' => 'id']],
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'deal_id' => Yii::t('app', 'Deal ID'),
            'name' => Yii::t('app', 'Image'),
            'description' => Yii::t('app', 'Description'),
            'size' => Yii::t('app', 'Size'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDeal()
    {
        return $this->hasOne(Deal::className(), ['id' => 'deal_id'])->inverseOf('dealGalleries');
    }

    public function upload()
    {
        if (!$this->validate()) {
            return False;
        }

        if ($this->isNewRecord) {
            $file_name = time() . '.' . $this->imageFile->extension;
        } else {
            $file_name = $this->name;
        }
        $image_save_path = \Yii::getAlias('@image_uploads/deals/');
        if (!file_exists($image_save_path)) {
            mkdir($image_save_path, 0755);
        }

        if ($this->imageFile) {
            $orignal_file_full_path = $image_save_path . $this->deal_id . '_orignal_' . $file_name;
            $saved_orignal = $this->imageFile->saveAs($orignal_file_full_path);
            $icons = [
                'large' => [
                    'width' => 900,
                    'height' => 600
                ],
                'medium' => [
                    'width' => 425,
                    'height' => 250
                ],
                'small' => [
                    'width' => 200,
                    'height' => 130
                ]
            ];

            if ($saved_orignal) {
                foreach ($icons as $size => $icon) {
                    Image::thumbnail($orignal_file_full_path, $icon['width'], $icon['height'])
                            ->save($image_save_path . $this->deal_id . '_' . $size . '_' . $file_name, array('jpeg_quality' => 100));
                }
                return $file_name;
            }
        }

        return False;
    }

    public function getIconURL($size = 'medium', $full = True)
    {
        $file_name = $this->deal_id . '_' . $size . '_' . $this->name;

        return \yii\helpers\Url::toRoute([((\Yii::$app->id == 'app-backend') ? ".." : "") . '/uploads/deals/' . $file_name], $full);
    }

}

backend/controllers/DealGalleryController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Deal;
use common\models\DealGallery;
use common\models\DealGallerySearch;
use backend\controllers\GenxUseAdminController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\Url;
use common\models\User;

/**
 * DealGalleryController implements the CRUD actions for DealGallery model.
 */
class DealGalleryController extends GenxUseAdminController
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $parent_behavior = parent::behaviors();
        $parent_behavior['access']['rules'][] = [
            'allow' => True,
            'actions' => [],
            'roles' => [User::ROLE_MERCHANT]
        ];

        return $parent_behavior;
    }

    /**
     * Lists all DealGallery models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DealGallerySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single DealGallery model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new DealGallery model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($deal_id)
    {
        $deal_model = Deal::findOne($deal_id);
        if (!$deal_model) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        $model = new DealGallery();
        $model->deal_id = $deal_model->id;

        $searchModel = new DealGallerySearch();
        $dataProvider = $searchModel->search([]);
        $dataProvider->query->andWhere(['deal_id' => $model->deal_id])->orderBy("sort_order asc");

        if ($model->load(Yii::$app->request->post())) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            $model->name = $model->imageFile->getBaseName();
            if ($name = $model->upload()) {
                $model->name = $name;
                if (!$model->save(False)) {
                    $this->sendErrors($model->getErrors());
                }else{
                    if (!Yii::$app->user->isAdmin()) {
                             $deal_model->disable();
                }
            $this->sendSuccess(["Deal photo uploaded successfully."]);
                }
                
            }

            return $this->refresh();
        }

        return $this->render('create', [
                    'model' => $model,
                    'deal_model' => $deal_model,
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Updates an existing DealGallery model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
       
        $checkupdate=Yii::$app->request->post();
        $model = $this->findModel($id);
        $deal_model=$model->deal;
        //$deal_model = Deal::findOne($model->deal_id);
        $searchModel = new DealGallerySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deal_id' => $model->deal_id])->orderBy("sort_order asc");

        if ($model->load(Yii::$app->request->post())) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($name = $model->upload()) {
                $model->name = $name;
            }

            if (!$model->save(False)) {
                $this->sendErrors($model->getErrors());
            } else {
                if (!Yii::$app->user->isAdmin()) {
                    
                 $deal_model->disable();
            }
            
            $this->sendSuccess(["Deal photo uploaded successfully."]);
            
             if(isset($checkupdate['update_id'])) {
               return $this->redirect(['create', 'deal_id' => $model->deal_id,'update_id'=>1]); 
            } 
            else{
                return $this->redirect(['create', 'deal_id' => $model->deal_id]);
            }
            }
        }

        return $this->render('update', [
                    'model' => $model,
                    'deal_model' => $deal_model,
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Deletes an existing DealGallery model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $dealgallery = $this->findModel($id);
        //echo $dealgallery->deal_id;
        //$deal=$dealgallery->deal;
        //    \common\components\GenXHelper::c($dealgallery);   
        $dealgallery->delete();
        return $this->redirect(Url::toRoute(["deal-gallery/create", 'deal_id' => $dealgallery->deal_id]));
    }

    /**
     * Finds the DealGallery model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DealGallery the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DealGallery::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

backend/views/deal-gallery/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\DealGallery */
/* @var $form yii\widgets\ActiveForm */
?>
<h4>
    <?= $deal_model->title ?>
</h4>
<div class="panel">
    <div class="panel-body">
        <!-- Steps -->
        <div id="wizard" class="form_wizard wizard_horizontal">
            <ul class="wizard_steps">
                <li>
                    <a href="#step-1" class="done">
                        <span class="step_no">1</span>
                        <span class="step_descr">
                            Step 1<br />
                            <small>Update Deal</small>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#step-2"  class="done">
                        <span class="step_no">2</span>
                        <span class="step_descr">
                            Step 2<br />
                            <small>Deal options</small>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#step-3" class="done">
                        <span class="step_no">3</span>
                        <span class="step_descr">
                            Step 3<br />
                            <small>Deal Addresses</small>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#step-4" class="selected">
                        <span class="step_no">4</span>
                        <span class="step_descr">
                            Step 4<br />
                            <small>Gallery for deal</small>
                        </span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- End Steps -->

        <!-- Wizard Content -->
        <div class="wizard-content">
            <div class="wizard-pane active">
                <div class="deal-gallery-form">

                    <?php
                    $form = ActiveForm::begin([
                                'options' => [
                                    'enctype' => 'multipart/form-data'
                                ]
                    ]);
                    ?>
                    <?= $form->field($model, 'imageFile')->fileInput(); ?>
                    <?= $form->field($model, 'description')->textInput(); ?>
                     <?php
                            if(isset($_REQUEST['update_id'])){
                                ?>
                            <input type="hidden" name="update_id" value="1">
                            <?php
                          }
                            ?>
                    <div class="row">
                        <div class="col-sm-8 col-xs-12">
                            <?= $form->field($model, 'deal_option_id')->dropDownList(yii\helpers\ArrayHelper::map(\common\models\DealOption::findAll(['deal_id' => $model->deal_id]), 'id', 'name'), ['prompt' => 'Select Option'])->label('Select if related to deal option'); ?>
                        </div>

                        <div class="col-sm-4 col-xs-12">
                             <?= $form->field($model, 'sort_order')->textInput(); ?>
                        </div>

                    </div>        
                    
                    <div class="form-group pull-right">
                        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Save') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>

                </div>
            </div>
        </div>
        <!-- End Wizard Content -->

    </div>
</div>

backend/views/deal-gallery/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\DealGallerySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="deal-gallery-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'deal_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'size') ?>

    <?= $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/deal-gallery/create.php
<?php

use yii\helpers\Html;
use common\components\GenXHelper;
use yii\helpers\Url;
use yii\grid\GridView;
use common\components\GenxGridHelper;

/* @var $this yii\web\View */
/* @var $model common\models\DealGallery */

$this->title = Yii::t('app', 'Create Deal Gallery');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Deal Galleries'), 'url' => ['deal/index']];
$this->params['breadcrumbs'][] = $this->title;
GenXHelper::contentHeader($this);
//GenXHelper::contentHeaderButtons($this, [
//    [
//        "title" => "List",
//        "url" => Url::toRoute(['/deal-gallery/index']),
//        "icon" => "fa fa-list",
//    ]
//]);
?>
<div class="deal-gallery-create panel">
    <div class="panel-body">
        <?=
        $this->render('_form', [
            'model' => $model,
            'deal_model' => $deal_model,
        ])
        ?>
    </div>
</div>

<div class="deal-option-index panel">
    <div class="panel-body">
        <?php 
if(!isset($_REQUEST['update_id']))
{
    
   $button = [

                                    'buttons' => [
                                        'edit' => function ($url, $model, $key) {
                                            $url = Url::toRoute(['update', 'id' => $model->id]);
                                            return Html::a('<span class="glyphicon glyphicon-pencil" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Update'),
                                                        'data-pjax' => '0',
                                            ]);
                                        },
                                             
                                                
                                                
                                                
                                               
                                                'delete' => function ($url, $model, $key) {

                                            $url = Url::toRoute(['delete', 'id' => $model->id]);
                                            return Html::a('<span class="glyphicon glyphicon-trash" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Delete'),
                                                        'data-confirm' => \Yii::t('yii', 'Are you sure to delete this deal?'),
                                                        'data-method' => 'post',
                                                        'data-pjax' => '0',
                                            ]);
                                        }
                                            ],
                                            'template' => '{edit} {delete} '
     ];
}
else{
    
    $button = [

                                    'buttons' => [
                                        'edit' => function ($url, $model, $key) {
                                            $url = Url::toRoute(['update', 'id' => $model->id,'update_id'=>1]);
                                            return Html::a('<span class="glyphicon glyphicon-pencil" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Update'),
                                                        'data-pjax' => '0',
                                            ]);
                                        },
                                             
                                                
                                                
                                                
                                               
                                                'delete' => function ($url, $model, $key) {

                                            $url = Url::toRoute(['delete', 'id' => $model->id,'update_id'=>1]);
                                            return Html::a('<span class="glyphicon glyphicon-trash" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Delete'),
                                                        'data-confirm' => \Yii::t('yii', 'Are you sure to delete this deal?'),
                                                        'data-method' => 'post',
                                                        'data-pjax' => '0',
                                            ]);
                                        }
                                            ],
                                            'template' => '{edit} {delete} '
     ];
    
}

// echo $this->render('_search', ['model' => $searchModel]); ?>
        <?=
        GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                [
                    'attribute' => 'name',
                    'format' => 'raw',
                    'value' => function($model) {
                        return Html::img($model->getIconURL('small'));
                    }
                ],
                'description',
                // 'updated_at',
                GenxGridHelper::ActionColumn($button),
            ],
        ]);
        ?>
        
        <?php
        
        if($deal_model->status ==  \common\models\Deal::STATUS_INCOMPLETE)
          {
        ?>    
        
            <?= Html::a('Back - Deal Address', ['/deal-address/create', 'deal_id' => $model->deal_id], ['class' => 'pull-left btn btn-primary']) ?>
       <?php 
        if ($dataProvider->getCount()) {
            echo Html::a('Finish', ['/deal/complete', 'id' => $model->deal_id], [
                'class' => 'pull-right btn btn-success',
                'data' => [
                    'confirm' => Yii::t('app', 'Deal will be submitted for Admin verification.'),
                    'method' => 'post',
                ]
            ]);
        }
        }
 else {
     echo Html::a('Submit', ['/deal/index'], ['class' => 'pull-right btn btn-success']);  
 }
        ?>
    </div>
</div>

backend/views/deal-gallery/index.php
<?php

use common\components\GenXHelper;
use common\components\GenxGridHelper;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\DealGallerySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Deal Galleries');
$this->params['breadcrumbs'][] = $this->title;
GenXHelper::contentHeader($this);
GenXHelper::contentHeaderButtons($this, [
    [
        "title" => "New",
        "url" => Url::toRoute(['/deal-gallery/create']),
        "icon" => "fa fa-plus",
    ],
    [
        "title" => "Refresh",
        "url" => Url::toRoute(['/deal-gallery/index']),
        "icon" => "fa fa-refresh",
    ],
]);
?>
<div class="deal-gallery-index panel">
    <div class="panel-body">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

              GenxGridHelper::linkedID(),
            'deal_id',
              GenxGridHelper::linkedTitle('name'),
            'size',
            // 'status',
            // 'created_at',
            // 'updated_at',

            GenxGridHelper::status(),
            GenxGridHelper::ActionColumn(),
        ],
    ]); ?>
    </div>
</div>

backend/views/deal-gallery/update.php
<?php

use yii\helpers\Html;
use common\components\GenXHelper;
use yii\helpers\Url;
use yii\grid\GridView;
use common\components\GenxGridHelper;

/* @var $this yii\web\View */
/* @var $model common\models\DealGallery */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
            'modelClass' => 'Deal Gallery',
        ]) . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Deal Galleries'), 'url' => ['deal/index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
GenXHelper::contentHeader($this);
GenXHelper::contentHeaderButtons($this, [
//    [
//        "title" => "List",
//        "url" => Url::toRoute(['/deal-gallery/index']),
//        "icon" => "fa fa-list",
//    ],
 /*   [
        "title" => "Delete",
        'data' => [
            'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
            'method' => 'post',
        ],
        "url" => Url::toRoute(['/deal-gallery/delete', 'id' => $model->id]),
        "icon" => "fa fa-trash",
    ],*/
]);
?>
<div class="deal-gallery-update panel">
    <div class="panel-body">
        <?=
        $this->render('_form', [
            'model' => $model,
            'deal_model' => $deal_model,
        ])
        ?>
    </div>
</div>

<div class="deal-option-index panel">
    <div class="panel-body">
        <?php 

if(!isset($_REQUEST['update_id']))
{
    
   $button = [

                                    'buttons' => [
                                        'edit' => function ($url, $model, $key) {
                                            $url = Url::toRoute(['update', 'id' => $model->id]);
                                            return Html::a('<span class="glyphicon glyphicon-pencil" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Update'),
                                                        'data-pjax' => '0',
                                            ]);
                                        },
                                             
                                                
                                                
                                                
                                               
                                                'delete' => function ($url, $model, $key) {

                                            $url = Url::toRoute(['delete', 'id' => $model->id]);
                                            return Html::a('<span class="glyphicon glyphicon-trash" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Delete'),
                                                        'data-confirm' => \Yii::t('yii', 'Are you sure to delete this deal?'),
                                                        'data-method' => 'post',
                                                        'data-pjax' => '0',
                                            ]);
                                        }
                                            ],
                                            'template' => '{edit} {delete} '
     ];
}
else{
    
    $button = [

                                    'buttons' => [
                                        'edit' => function ($url, $model, $key) {
                                            $url = Url::toRoute(['update', 'id' => $model->id,'update_id'=>1]);
                                            return Html::a('<span class="glyphicon glyphicon-pencil" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Update'),
                                                        'data-pjax' => '0',
                                            ]);
                                        },
                                             
                                                
                                                
                                                
                                               
                                                'delete' => function ($url, $model, $key) {

                                            $url = Url::toRoute(['delete', 'id' => $model->id,'update_id'=>1]);
                                            return Html::a('<span class="glyphicon glyphicon-trash" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Delete'),
                                                        'data-confirm' => \Yii::t('yii', 'Are you sure to delete this deal?'),
                                                        'data-method' => 'post',
                                                        'data-pjax' => '0',
                                            ]);
                                        }
                                            ],
                                            'template' => '{edit} {delete} '
     ];
    
}

// echo $this->render('_search', ['model' => $searchModel]); ?>
        <?=
        GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                [
                    'attribute' => 'name',
                    'format' => 'raw',
                    'value' => function($model) {
                        return Html::img($model->getIconURL('small'));
                    }
                ],
                'description',
                // 'updated_at',
                GenxGridHelper::ActionColumn($button),
            ],
        ]);
        ?>
        <?php
        //if(!isset($_REQUEST['update_id'])){
          if($deal_model->status ==  \common\models\Deal::STATUS_INCOMPLETE)
          { 
            
            
        ?>
        <?= Html::a('Back - Deal Options', ['/deal-option/create', 'deal_id' => $model->deal_id], ['class' => 'pull-left btn btn-primary']) ?>
        <?=
        Html::a('Finish', ['/deal/complete', 'id' => $model->deal_id], [
            'class' => 'pull-right btn btn-success',
            'data' => [
                'confirm' => Yii::t('app', 'Deal will be submitted for Admin verification.'),
                'method' => 'post',
            ]
        ])
        ?>
        <?php
        }
        else{
             
             echo Html::a('Submit', ['/deal/index'], ['class' => 'pull-right btn btn-success']);  
        }
        
        ?>
    </div>
</div>

backend/views/deal-gallery/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\DealGallery */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Deal Galleries'), 'url' => ['deal/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="deal-gallery-view">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'deal_id',
            'name',
            'size',
            'status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>