backend/controllers/DealAddressController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\DealAddress;
use common\models\DealAddressSearch;
use backend\controllers\GenxUseAdminController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\Deal;
use common\models\User;
use yii\helpers\Url;

/**
 * DealOptionController implements the CRUD actions for DealOption model.
 */
class DealAddressController extends GenxUseAdminController
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $parent_behavior = parent::behaviors();
        $parent_behavior['access']['rules'][] = [
            'allow' => True,
            'actions' => [],
            'roles' => [User::ROLE_MERCHANT]
        ];

        return $parent_behavior;
    }

    /**
     * Lists all DealOption models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DealAddressSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single DealOption model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new DealOption model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($deal_id)
    {
        if(Yii::$app->user->isAdmin())
        {    

        // exit;
        $deal_model = Deal::findOne($deal_id);
        if (!$deal_model) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
        $model = new DealAddress();
        
        $merchant = Yii::$app->user->merchant();
        if ($merchant && $merchant->company) {
            $model->geo_lat = $merchant->company->geo_lat;
            $model->geo_long = $merchant->company->geo_long;
        }
        $model->deal_id = $deal_model->id;
        $searchModel = new DealAddressSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deal_id' => $model->deal_id]);
        // gurmeet: Setting it default to one, so that we can show it checked
        // by default in form
        if (!Yii::$app->request->post()) {
            $model->show_address = 1;
            $model->show_name = 1;
        }
        else{
        // save city and state    
            $getdeal = Yii::$app->request->post();
            $cityvalue= \common\models\City::findOne($getdeal['DealAddress']['city_id']);
            $model->state_id = $cityvalue->state_id;
        }
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            if (!Yii::$app->user->isAdmin()) {
                $deal_model->disable();
            }
            $this->sendSuccess(["Deal Address created successfully."]);
            return $this->refresh();
        } else {
            \common\components\GenXHelper::DevErrors($model->getErrors());
        }

        return $this->render('create', [
                    'model' => $model,
                    'deal_model' => $deal_model,
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
        }
        else{
		      return $this->redirect(\yii\helpers\Url::toRoute(['/deal/index']));
        }
    }

    /**
     * Updates an existing DealOption model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if(Yii::$app->user->isAdmin())
        {    

        $checkupdate = Yii::$app->request->post();
        $model = $this->findModel($id);
        $deal_model = Deal::findOne($model->deal_id);
        $searchModel = new DealAddressSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deal_id' => $model->deal_id]);

        //\common\components\GenXHelper::c($checkupdate);
        if($checkupdate)
            {
            $cityvalue= \common\models\City::findOne($checkupdate['DealAddress']['city_id']);
            $model->state_id = $cityvalue->state_id;
            }
            
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (!Yii::$app->user->isAdmin()) {
                $deal_model->disable();
            }
            $this->sendSuccess(["Deal Address updated successfully."]);
            if (isset($checkupdate['update_id'])) {
                return $this->redirect(['create', 'deal_id' => $model->deal_id, 'update_id' => 1]);
            } else {
                return $this->redirect(['create', 'deal_id' => $model->deal_id]);
            }
        } else {
            $this->sendErrors($model->getErrors());
        }

        return $this->render('update', [
                    'model' => $model,
                    'deal_model' => $deal_model,
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
        
        
        }
         else{
		      return $this->redirect(\yii\helpers\Url::toRoute(['/deal/index']));
        }
    }

    /**
     * Deletes an existing DealOption model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $deal_address = $this->findModel($id);
        $deal_address->delete();

        return $this->redirect(Url::toRoute(["deal-address/create", 'deal_id' => $deal_address->deal_id]));
    }

    /**
     * Finds the DealOption model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DealOption the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DealAddress::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

backend/views/deal-address/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\DealOption */
/* @var $form yii\widgets\ActiveForm */
?>
<!-- Panel Wizard Form -->
<h4>
    <?= $deal_model->title ?>
</h4>
<div class="panel">
    <div class="panel-body">
        <!-- Steps -->
        <div id="wizard" class="form_wizard wizard_horizontal">
            <ul class="wizard_steps">
                <li>
                    <a href="#step-1" class="done">
                        <span class="step_no">1</span>
                        <span class="step_descr">
                            Step 1<br />
                            <small>Update Deal</small>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#step-2" class="done">
                        <span class="step_no">2</span>
                        <span class="step_descr">
                            Step 2<br />
                            <small>Deal options</small>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#step-3" class="selected">
                        <span class="step_no">3</span>
                        <span class="step_descr">
                            Step 3<br />
                            <small>Deal Address</small>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#step-4">
                        <span class="step_no">4</span>
                        <span class="step_descr">
                            Step 4<br />
                            <small>Gallery for deal</small>
                        </span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- End Steps -->

        <!-- Wizard Content -->
        <div class="wizard-content">
            <div class="wizard-pane active">
                <div class="deal-option-form">
                    <div class="row">
                        <?php $form = ActiveForm::begin(); ?>

                        <div class="row">
                            <div class="col-lg-12">
                                <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>
                                <div class="col-lg-6">
                              
                                <?=  $this->render('@common/views/_partials/city', ['form' => $form, 'model' => $model, 'attribute' => 'city_id']); ?>
                                </div>
                                
                                <div class="col-lg-6">
                                
                                <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
                                </div>
                                
                                <div class="col-lg-6">
                                    <?= $form->field($model, 'show_name')->checkBox(['label' => 'Show Name']) ?>
                                </div>    
                                <div class="col-lg-6">
                                    <?= $form->field($model, 'show_address')->checkBox(['label' => 'Show Address']) ?>
                                </div>    
                                <?= $form->field($model, 'geo_lat')->hiddenInput()->label(False); ?>
                                <?= $form->field($model, 'geo_long')->hiddenInput()->label(False); ?>
                                <?php if (isset($_REQUEST['update_id'])) { ?>
                                    <input type="hidden" name="update_id" value="1">
                                <?php } ?>
                                
                                <div class="col-lg-12">
                                    
                                    
                                    <label class="control-label">Select your Location</label>

                                <?=
                                $this->render('@common/views/_partials/gmap_geolocation', [
                                    'form' => $form,
                                    'model' => $model,
                                    'options' => [
                                        'address_input_id' => 'dealaddress-address',
                                        'lat_input_id' => 'dealaddress-geo_lat',
                                        'long_input_id' => 'dealaddress-geo_long',
                                    ]
                                ]);
                                ?>
                                </div>
                            </div>
                        </div>

                        <div class="form-group pull-right">
                            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                        </div>




                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
        <!-- End Wizard Content -->

    </div>
</div>

<?php
//$this->registerJs("
//   $('#dealaddress-address').geocomplete();
//");
?>

backend/views/deal-address/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\DealOptionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="deal-option-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'deal_id') ?>

    <?= $form->field($model, 'address') ?>

    <?php //$form->field($model, 'slug') ?>

    <?php //$form->field($model, 'list_price') ?>

    <?php // echo $form->field($model, 'selling_price') ?>

    <?php // echo $form->field($model, 'no_per_person') ?>

    <?php // echo $form->field($model, 'total_sold') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/deal-address/create.php
<?php

use yii\helpers\Html;
use common\components\GenXHelper;
use yii\helpers\Url;
use yii\grid\GridView;
use common\components\GenxGridHelper;

/* @var $this yii\web\View */
/* @var $model common\models\DealOption */

$this->title = Yii::t('app', 'Create Deal Address');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Deal Address'), 'url' => ['deal/index']];
$this->params['breadcrumbs'][] = $this->title;
GenXHelper::contentHeader($this);
//GenXHelper::contentHeaderButtons($this, [
//    [
//        "title" => "List",
//        "url" => Url::toRoute(['/deal-address/index']),
//        "icon" => "fa fa-list",
//    ]
//]);
?>
<div class="deal-option-create panel">
    <div class="panel-body">
        <?=
        $this->render('_form', [
            'model' => $model,
            'deal_model' => $deal_model,
        ])
        ?>
    </div>
</div>
<div class="deal-option-index panel">
    <div class="panel-body">
        <?php
        if (!isset($_REQUEST['update_id'])) {

            $button = [

                'buttons' => [
                    'edit' => function ($url, $model, $key) {
                        $url = Url::toRoute(['update', 'id' => $model->id]);
                        return Html::a('<span class="glyphicon glyphicon-pencil" style="font-size:20px;"></span>', $url, [
                                    'title' => \Yii::t('yii', 'Update'),
                                    'data-pjax' => '0',
                        ]);
                    },
                            'delete' => function ($url, $model, $key) {

                        $url = Url::toRoute(['delete', 'id' => $model->id]);
                        return Html::a('<span class="glyphicon glyphicon-trash" style="font-size:20px;"></span>', $url, [
                                    'title' => \Yii::t('yii', 'Delete'),
                                    'data-confirm' => \Yii::t('yii', 'Are you sure to delete this deal?'),
                                    'data-method' => 'post',
                                    'data-pjax' => '0',
                        ]);
                    }
                        ],
                        'template' => '{edit} {delete} '
                    ];
                } else {

                    $button = [

                        'buttons' => [
                            'edit' => function ($url, $model, $key) {
                                $url = Url::toRoute(['update', 'id' => $model->id, 'update_id' => 1]);
                                return Html::a('<span class="glyphicon glyphicon-pencil" style="font-size:20px;"></span>', $url, [
                                            'title' => \Yii::t('yii', 'Update'),
                                            'data-pjax' => '0',
                                ]);
                            },
                                    'delete' => function ($url, $model, $key) {

                                $url = Url::toRoute(['delete', 'id' => $model->id, 'update_id' => 1]);
                                return Html::a('<span class="glyphicon glyphicon-trash" style="font-size:20px;"></span>', $url, [
                                            'title' => \Yii::t('yii', 'Delete'),
                                            'data-confirm' => \Yii::t('yii', 'Are you sure to delete this deal?'),
                                            'data-method' => 'post',
                                            'data-pjax' => '0',
                                ]);
                            }
                                ],
                                'template' => '{edit} {delete} '
                            ];
                        }


// echo $this->render('_search', ['model' => $searchModel]); 
                        ?>
                        <?=
                        GridView::widget([
                            'dataProvider' => $dataProvider,
                            'filterModel' => $searchModel,
                            'columns' => [
                                ['class' => 'yii\grid\SerialColumn'],
                                'address',
                                'geo_long',
                                'geo_lat',
                                // 'status',
                                // 'created_at',
                                // 'updated_at',
                                GenxGridHelper::ActionColumn($button),
                            ],
                        ]);
                        ?>
                        <?php
                        if (!isset($_REQUEST['update_id'])) {
                            ?>
                            <?= Html::a('Back - Update Deal Options', ['/deal-option/create', 'deal_id' => $model->deal_id], ['class' => 'pull-left btn btn-primary']) ?>
                            <?php
                            if ($dataProvider->getCount()) {
                                echo Html::a('Next - Update Gallery', ['/deal-gallery/create', 'deal_id' => $model->deal_id], ['class' => 'pull-right btn btn-primary']);
                            }
                            ?>
                            <?php
                        } else {
                            echo Html::a('Finish', ['/deal/index'], ['class' => 'pull-right btn btn-success']);
                        }
                        ?>
    </div>
</div>

backend/views/deal-address/index.php
<?php

use common\components\GenXHelper;
use common\components\GenxGridHelper;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\DealOptionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Deal Address');
$this->params['breadcrumbs'][] = $this->title;
GenXHelper::contentHeader($this);
GenXHelper::contentHeaderButtons($this, [
    [
        "title" => "New",
        "url" => Url::toRoute(['/deal-address/create']),
        "icon" => "fa fa-plus",
    ],
    [
        "title" => "Refresh",
        "url" => Url::toRoute(['/deal-address/index']),
        "icon" => "fa fa-refresh",
    ],
]);
?>
<div class="deal-option-index panel">
    <div class="panel-body">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

              GenxGridHelper::linkedID(),
            'deal_id',
              GenxGridHelper::linkedTitle('name'),
            'slug',
            // 'list_price',
            // 'selling_price',
            // 'no_per_person',
            // 'total_sold',
            // 'status',
            // 'created_at',
            // 'updated_at',

            GenxGridHelper::status(),
            GenxGridHelper::ActionColumn(),
        ],
    ]); ?>
    </div>
</div>

backend/views/deal-address/update.php
<?php

use yii\helpers\Html;
use common\components\GenXHelper;
use yii\helpers\Url;
use yii\grid\GridView;
use common\components\GenxGridHelper;

/* @var $this yii\web\View */
/* @var $model common\models\DealOption */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
            'modelClass' => 'Deal Address',
        ]) . $model->address;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Deal Address'), 'url' => ['deal/index']];
$this->params['breadcrumbs'][] = ['label' => $model->address, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
GenXHelper::contentHeader($this);
GenXHelper::contentHeaderButtons($this, [
//    [
//        "title" => "List",
//        "url" => Url::toRoute(['/deal-address/index']),
//        "icon" => "fa fa-list",
//    ],
    [
        "title" => "Delete",
        'data' => [
            'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
            'method' => 'post',
        ],
        "url" => Url::toRoute(['/deal-address/delete', 'id' => $model->id]),
        "icon" => "fa fa-trash",
    ],
]);
?>
<div class="deal-option-update panel">
    <div class="panel-body">
        <?=
        $this->render('_form', [
            'model' => $model,
            'deal_model' => $deal_model,
        ])
        ?>
    </div>
</div>

<div class="deal-option-index panel">
    <div class="panel-body">
        <?php
        
if(!isset($_REQUEST['update_id']))
{
    
   $button = [

                                    'buttons' => [
                                        'edit' => function ($url, $model, $key) {
                                            $url = Url::toRoute(['update', 'id' => $model->id]);
                                            return Html::a('<span class="glyphicon glyphicon-pencil" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Update'),
                                                        'data-pjax' => '0',
                                            ]);
                                        },
                                             
                                                
                                                
                                                
                                               
                                                'delete' => function ($url, $model, $key) {

                                            $url = Url::toRoute(['delete', 'id' => $model->id]);
                                            return Html::a('<span class="glyphicon glyphicon-trash" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Delete'),
                                                        'data-confirm' => \Yii::t('yii', 'Are you sure to delete this deal?'),
                                                        'data-method' => 'post',
                                                        'data-pjax' => '0',
                                            ]);
                                        }
                                            ],
                                            'template' => '{edit} {delete} '
     ];
}
else{
    
    $button = [

                                    'buttons' => [
                                        'edit' => function ($url, $model, $key) {
                                            $url = Url::toRoute(['update', 'id' => $model->id,'update_id'=>1]);
                                            return Html::a('<span class="glyphicon glyphicon-pencil" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Update'),
                                                        'data-pjax' => '0',
                                            ]);
                                        },
                                             
                                                
                                                
                                                
                                               
                                                'delete' => function ($url, $model, $key) {

                                            $url = Url::toRoute(['delete', 'id' => $model->id,'update_id'=>1]);
                                            return Html::a('<span class="glyphicon glyphicon-trash" style="font-size:20px;"></span>', $url, [
                                                        'title' => \Yii::t('yii', 'Delete'),
                                                        'data-confirm' => \Yii::t('yii', 'Are you sure to delete this deal?'),
                                                        'data-method' => 'post',
                                                        'data-pjax' => '0',
                                            ]);
                                        }
                                            ],
                                            'template' => '{edit} {delete} '
     ];
    
}
        ?>
        <?=
        GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'address',
                'geo_long',
                'geo_lat',
                
                // 'status',
                // 'created_at',
                // 'updated_at',
                GenxGridHelper::ActionColumn($button),
            ],
        ]);
        ?>
        <?php
        if(!isset($_REQUEST['update_id'])){
        ?>
        <?= Html::a('Back - Update Deal', ['/deal/update', 'id' => $model->deal_id], ['class' => 'pull-left btn btn-primary']) ?>
        <?= Html::a('Next - Update Gallery', ['/deal-gallery/create', 'deal_id' => $model->deal_id], ['class' => 'pull-right btn btn-primary']) ?>
        <?php
        }
         else{
           echo Html::a('Finish', ['/deal/index'], ['class' => 'pull-right btn btn-success']);  
                 }
        ?>
    </div>
</div>

backend/views/deal-address/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\DealOption */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Deal Address'), 'url' => ['deal/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="deal-option-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this address?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'deal_id',
            'address',
            'geo_long',
            'geo_lat',
            'status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>