common/models/City.php
<?php

namespace common\models;

use yii\imagine\Image;
use Yii;

/**
 * This is the model class for table "{{%city}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property string $iso_2_char
 * @property string $iso_3_char
 * @property string $iso_4_char
 * @property integer $country_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $status
 * @property integer $latitude
 * @property integer $longitude
 * @property integer $zip_code
 * @property integer $search_name
 * @property integer $featured
 *
 * @property Country $country
 * @property State $state
 * @property ServiceRequest[] $serviceRequests
 */
class City extends \common\components\GenxBaseModel
{

    public $imageFile;
    public $total_deals_in_city;

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors[] = [
            'class' => \yii\behaviors\SluggableBehavior::className(),
            'attribute' => 'name',
            'ensureUnique' => True
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%city}}';
    }

    /**
     * @inheritdoc
     */
    public function rules($rules = array())
    {
        return parent::rules([
                    [['name', 'slug', 'country_id', 'state_id'], 'required'],
                    [['country_id', 'state_id', 'featured', 'show_home', 'status', 'default_city'], 'integer'],
                    [['name', 'slug', 'featured_img'], 'string', 'max' => 255],
                    [['iso_2_char'], 'string', 'max' => 2],
                    [['iso_3_char'], 'string', 'max' => 3],
                    [['iso_4_char'], 'string', 'max' => 4]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'slug' => Yii::t('app', 'Slug'),
            'iso_2_char' => Yii::t('app', 'Iso 2 Char'),
            'iso_3_char' => Yii::t('app', 'Iso 3 Char'),
            'iso_4_char' => Yii::t('app', 'Iso 4 Char'),
            'country_id' => Yii::t('app', 'Country ID'),
            'state_id' => Yii::t('app', 'State ID'),
            'featured' => Yii::t('app', 'Features'),
            'show_home' => Yii::t('app', 'Show Homepage'),
            'featured_img' => Yii::t('app', 'Features Image'),
            'default_city' => Yii::t('app', 'Default City'),
        ];
    }

    public function upload()
    {
        if (!$this->validate()) {
            return False;
        }

        /* if ($this->isNewRecord) {
          $file_name = time() . '.' . $this->imageFile->extension;
          } else {
          $file_name = $this->name;
          } */

        $file_name = "city_" . $this->slug . '.' . $this->imageFile->extension;
        $image_save_path = \Yii::getAlias('@image_uploads/banner/');

        $orignal_file_full_path = $image_save_path . $file_name;
        $saved_orignal = $this->imageFile->saveAs($orignal_file_full_path);
        Image::thumbnail($orignal_file_full_path, 241, 250)->save($image_save_path . $file_name);

        if ($saved_orignal) {
            return $file_name;
        }

        return False;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCountry()
    {
        return $this->hasOne(Country::className(), ['id' => 'country_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(State::className(), ['id' => 'state_id']);
    }

    public function getURL($action = 'view', $only_route = False, $full_url = False)
    {
        return parent::getURL("/city/view", $only_route, $full_url);
    }

    public function getCompanies()
    {
        return $this->hasOne(Company::className(), ['city_id' => 'id'])->inverseOf('city');
    }

    /**
     * 
     * @inheritdoc
     * @return ActiveQuery the newly created [[ActiveQuery]] instance.
     */
    public static function getTopCities($options = array())
    {
        $find = self::find()
                ->select('city.*, count(deal.city_id) as total_deals_in_city')
                ->innerJoin('deal', 'deal.city_id = city.id')
                ->groupBy('`deal`.city_id')
                ->orderBy('total_deals_in_city DESC');

        if (isset($options['andFilterWhere']) && sizeof($options['andFilterWhere'])) {
            foreach ($options['andFilterWhere'] as $andFilterWhere) {
                $find->andFilterWhere($andFilterWhere);
            }
        }

        return $find;
    }

    public static function getSelectedDefaultCity()
    {
        if (!isset(static::$_CACHE['getSelectedDefaultCity'])) {
            $find = self::find()->andWhere(['default_city' => 1])->one();
            static::$_CACHE['getSelectedDefaultCity'] = $find->getAttributes();
        }

        return static::$_CACHE['getSelectedDefaultCity'];
    }

    public static function getFeaturedCity($options = array())
    {
        $find = self::find()
                ->select('city.*')
                ->andWhere(['featured' => 1]);

        if (isset($options['andFilterWhere']) && sizeof($options['andFilterWhere'])) {
            foreach ($options['andFilterWhere'] as $andFilterWhere) {
                $find->andFilterWhere($andFilterWhere);
            }
        }

        return $find;
    }

    public static function getNearBy($lat, $long, $radius_in_miles)
    {
        $find = self::find()
                ->select('city.*, ( 3959 * acos( cos( radians(' . $lat . ') ) * cos( radians( city.latitude ) ) * cos( radians( city.longitude ) - radians(' . $long . ') ) + sin( radians(' . $lat . ') ) * sin( radians( city.latitude ) ) ) ) AS distance')
                ->having(['<', 'distance', $radius_in_miles])
                ->orderBy('distance');

        return $find;
    }

    public function getBannerURL($full = True)
    {
        $file_name = $this->featured_img;

        return \yii\helpers\Url::toRoute([((\Yii::$app->id == 'app-backend') ? ".." : "") . '/uploads/banner/' . $file_name], $full);
    }

}

backend/controllers/CityController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\City;
use common\models\CitySearch;
use backend\controllers\GenxUseAdminController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\User;
use yii\web\UploadedFile;

/**
 * CityController implements the CRUD actions for City model.
 */
class CityController extends GenxUseAdminController
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $parent_behavior = parent::behaviors();
        $parent_behavior['access']['rules'][] = [
            'allow' => True,
            'actions' => [],
            'roles' => [User::ROLE_ADMIN]
        ];
        $parent_behavior['access']['rules'][] = [
            'allow' => True,
            'actions' => ['autocomplete'],
            'roles' => [User::ROLE_MERCHANT]
        ];

        return $parent_behavior;
    }

    /**
     * Lists all City models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CitySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
       // \common\components\GenXHelper::c($dataProvider);
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single City model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new City model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new City();
        $model->country_id = Yii::$app->request->get('country_id', 0);
        $model->state_id = Yii::$app->request->get('state_id', 0);
        
        
        if ($model->load(Yii::$app->request->post())) {
        
        $statedata= \common\models\State::findOne($model->state_id);
        
            
            $model->imageFile = UploadedFile::getInstance($model, 'featured_img');
            if($model->imageFile){
            $model->featured_img = $model->imageFile->getBaseName();
            if ($featured_img = $model->upload()) {
                $model->featured_img = $featured_img;
                
                }
            }
            // google api work
            
            $address =  $model->name.", ".$statedata->name;
            $address = urlencode($address);
            $googleApi = new \common\components\GoogleApiEx($address);
            $data=$googleApi->getInfo();
            $model->latitude = $data['results'][0]['geometry']['location']['lat'];
            $model->longitude =  $data['results'][0]['geometry']['location']['lng'];
            if(!$model->save()){
                    $this->sendErrors($model->getErrors());
                }
          
                
            return $this->redirect(['view', 'id' => $model->id]);
        
            
            } 
        else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }
    

    /**
     * Updates an existing City model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            
            $model->imageFile = UploadedFile::getInstance($model, 'featured_img');
            if($model->imageFile){
            $featured_img = $model->imageFile->getBaseName();
            if ($featured_img = $model->upload()) {
                $model->featured_img = $featured_img;
                
                }
            }
            else{
                $model->featured_img=$model->getOldAttribute("featured_img");
            }
            
            $address= $model->search_name;
            $address = urlencode($address);
            // google api work
            $googleApi = new \common\components\GoogleApiEx($address);
            $data=$googleApi->getInfo();
            $model->latitude = $data['results'][0]['geometry']['location']['lat'];
            $model->longitude =  $data['results'][0]['geometry']['location']['lng'];
            
                if(!$model->save()){
                    $this->sendErrors($model->getErrors());
                }
            
            
            return $this->redirect(['index', 'CitySearch[id]' => $model->id]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }
    
    public function actionAllCityUpdated()
    {
        $allrecord = City::find()
                ->Where(['done'=>0,
                    'status'=>10])
                //->andWhere(['status'=>10])
                ->limit(25)->all();
        foreach ($allrecord as $citymodel)
        {
            
             $address= $citymodel->search_name;
            $address = urlencode($address);
            
            $googleApi = new \common\components\GoogleApiEx($address);
            $data=$googleApi->getInfo();
            $citymodel->latitude = $data['results'][0]['geometry']['location']['lat'];
            $citymodel->longitude =  $data['results'][0]['geometry']['location']['lng'];
            $citymodel->done=1;
             if($citymodel->save())
             {   
            \common\components\GenXHelper::c($citymodel['search_name']);
             }
        }
    }

    /**
     * Deletes an existing City model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the City model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return City the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = City::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAutocomplete($term = Null)
    {

        $city_search_options = [];
        $term = trim($term);
        if (empty($term)) {
            $city_search_options[] = ['featured' => 1];
        }

        $city_data_query = City::find()->andFilterWhere(['like', 'search_name', $term]);
        if (sizeof($city_search_options)) {
            foreach ($city_search_options as $filter) {
                $city_data_query->andWhere($filter);
            }
        }

        $city_data = $city_data_query->all();
        $return = [];
        if (sizeof($city_data)) {
            foreach ($city_data as $city) {
                $return['results'][] = [
                    'text' => $city->search_name,
                    'id' => $city->id
                ];
            }

            $return['more'] = False;
        }

        // send with json headers
        header('Content-Type: application/json');
        echo json_encode($return);
    }

}

backend/views/city/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\City */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="city-form">

    <?php $form = ActiveForm::begin([
                                'options' => [
                                    'enctype' => 'multipart/form-data'
                                ]
                    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    <?= $this->render("@common/views/_partials/country", ["model" => $model, "form" => $form]); ?>
    <?= $this->render("@common/views/_partials/state", ["model" => $model, "form" => $form]); ?>
    <?= $form->field($model, 'iso_2_char')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'iso_3_char')->textInput(['maxlength' => true]) ?>
    <?= $this->render("@common/views/_partials/status", ['model' => $model, 'form' => $form]); ?>
    <?= $form->field($model, 'featured')->dropDownList(common\components\GenxBaseModel::getFeaturedDropdown());?>
    <?= $form->field($model, 'featured_img')->fileInput(); ?>
     <?= $form->field($model, 'show_home')->dropDownList(common\components\GenxBaseModel::getFeaturedDropdown());?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/city/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\CitySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="city-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'slug') ?>

    <?= $form->field($model, 'iso_2_char') ?>

    <?= $form->field($model, 'iso_3_char') ?>

    <?php // echo $form->field($model, 'iso_4_char') ?>

    <?php // echo $form->field($model, 'country_id') ?>

    <?php // echo $form->field($model, 'state_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/city/create.php
<?php

use yii\helpers\Html;
use common\components\GenXHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\City */

$this->title = Yii::t('app', 'Create City');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Cities'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
GenXHelper::contentHeader($this);
GenXHelper::contentHeaderButtons($this, [
    [
        "title" => "List",
        "url" => Url::toRoute(['/state/index']),
        "icon" => "fa fa-list",
    ]
]);
?>
<div class="city-update panel">
    <div class="panel-body">
        <?=
        $this->render('_form', [
            'model' => $model,
        ])
        ?>

    </div>
</div>

backend/views/city/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\components\GenxGridHelper;
use common\components\GenXHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel common\models\CitySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Cities');
$this->params['breadcrumbs'][] = $this->title;
GenXHelper::contentHeader($this);
GenXHelper::contentHeaderButtons($this, [
    [
        "title" => "New",
        "url" => Url::toRoute(['/city/create']),
        "icon" => "fa fa-plus",
    ],
    [
        "title" => "Refresh",
        "url" => Url::toRoute(['/city/index']),
        "icon" => "fa fa-refresh",
    ],
]);
?>
<div class="city-index panel">
    <div class="panel-body">
        <div class="table-responsive">
        <?php

        $dataProvider->sort = [
            'attributes' => ['id', 'name']
        ];
       echo GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                GenxGridHelper::linkedID(),
                GenxGridHelper::linkedTitle('name'),
                'zip_code',
                GenxGridHelper::states(),
                GenxGridHelper::status(),
                GenxGridHelper::featured(),
                 [
                    'label' => 'Featured Image',
                    'attribute' => 'featured_img',
                    
                ],
                [
                    'label' => 'Show Homepage',
                    'attribute'=>'show_home',
                    'filter'=>array("1"=>"Active","0"=>"InActive")
                ],
                
                GenxGridHelper::ActionColumn(),
            ],
        ]);
        ?>
    </div>
    </div>
</div>

backend/views/city/update.php
<?php

use yii\helpers\Html;
use common\components\GenXHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\City */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
            'modelClass' => 'City',
        ]) . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Cities'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
GenXHelper::contentHeader($this);
GenXHelper::contentHeaderButtons($this, [
    [
        "title" => "List",
        "url" => Url::toRoute(['/city/index']),
        "icon" => "fa fa-list",
    ],
    [
        "title" => "Delete",
        'data' => [
            'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
            'method' => 'post',
        ],
        "url" => Url::toRoute(['/city/delete', 'id' => $model->id]),
        "icon" => "fa fa-trash",
    ],
]);
?>
<div class="city-update panel">
    <div class="panel-body">
        <?=
        $this->render('_form', [
            'model' => $model,
        ])
        ?>
    </div>
</div>

backend/views/city/view.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\components\GenXHelper;
use common\components\GenxGridHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\City */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Cities'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
GenXHelper::contentHeader($this);
GenXHelper::contentHeaderButtons($this, [
    [
        "title" => "Edit",
        "url" => Url::toRoute(['/city/update', 'id' => $model->id]),
        "icon" => "fa fa-edit",
    ],
    [
        "title" => "Delete",
        'data' => [
            'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
            'method' => 'post',
        ],
        "url" => Url::toRoute(['/city/delete', 'id' => $model->id]),
        "icon" => "fa fa-trash",
    ],
    [
        "title" => "List",
        "url" => Url::toRoute(['/city/index']),
        "icon" => "fa fa-list",
    ]
]);
?>

<div class="category-view panel">
    <div class="panel-body">
        <h1>
            <?= Html::a($model->country->name, $model->country->getURL());?> : <?= Html::a($model->state->name, $model->state->getURL());?> : <?= $model->name; ?>
        </h1>
    </div>
</div>