common/models/DiscountcouponDetails.php
<?php

namespace common\models;

use Yii;
use yii\imagine\Image;

/**
 * This is the model class for table "discountcoupon_details".
 *
 * @property integer $id
 * @property string $discount_coupon
 * @property string $discount_title
 * @property string $slug
 * @property string $amount_type
 * @property integer $amount_value
 * @property integer $total_person_allow
 * @property integer $min_bill
 * @property integer $max_credit
 * @property integer $coupon_start_dt
 * @property integer $coupon_expire_dt
 * @property integer $total_qty
 * @property integer $total_used
 * @property integer $category
 * @property integer $deal
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $coupon_img
 * @property string $coupon_img_url
 * @property DiscountcouponCategory[] $discountcouponCategories
 * @property DiscountcouponDeal[] $discountcouponDeals
 */
class DiscountcouponDetails extends \common\components\GenxBaseModel
{

    public $imageFile;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'discountcoupon_details';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors[] = [
            'class' => \yii\behaviors\SluggableBehavior::className(),
            'attribute' => 'discount_coupon',
            'ensureUnique' => True
        ];

        return $behaviors;
    }

    public function rules($rules = [])
    {
        return parent::rules([
                    [['discount_coupon', 'discount_title', 'slug', 'amount_type', 'amount_value', 'total_person_allow', 'max_credit', 'coupon_start_dt', 'coupon_expire_dt'], 'required'],
                    [['amount_value', 'total_person_allow', 'min_bill', 'max_credit', 'coupon_start_dt', 'coupon_expire_dt', 'total_qty', 'total_used', 'category', 'deal'], 'integer'],
                    [['discount_coupon', 'discount_title', 'amount_type'], 'string', 'max' => 255],
                    [['coupon_img', 'coupon_img_url'], 'string'],
                    [['discount_coupon'], 'unique', 'targetAttribute' => ['discount_coupon']],
        ]);
    }

    public function beforeValidate()
    {


        if (strlen($this->coupon_start_dt) > 10) {
            $this->coupon_start_dt = (int) (substr($this->coupon_start_dt, 0, 10));
        }

        if (strlen($this->coupon_expire_dt) > 10) {
            $this->coupon_expire_dt = (int) (substr($this->coupon_expire_dt, 0, 10));
        }
        return parent::beforeValidate();
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'discount_coupon' => 'Discount Coupon',
            'discount_title' => 'Discount Title',
            'amount_type' => 'Amount Type',
            'slug' => Yii::t('app', 'Slug'),
            'amount_value' => 'Amount Value',
            'total_person_allow' => 'Total Person Allow',
            'min_bill' => 'Min Bill',
            'max_credit' => 'Max Credit',
            'coupon_start_dt' => 'Coupon Start Dt',
            'coupon_expire_dt' => 'Coupon Expire Dt',
            'total_qty' => 'Total Qty',
            'total_used' => 'Total Used',
            'category' => 'Category',
            'deal' => 'Deal',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'coupon_img' => 'Coupon Image',
            'coupon_img_url' => 'Coupon Image Url',
        ];
    }

    public function upload()
    {
        if (!$this->validate()) {
            return False;
        }

        /* if ($this->isNewRecord) {
          $file_name = time() . '.' . $this->imageFile->extension;
          } else {
          $file_name = $this->name;
          } */

        $file_name = "coupon_" . $this->slug . '.' . $this->imageFile->extension;
        $image_save_path = \Yii::getAlias('@image_uploads/banner/');

        $orignal_file_full_path = $image_save_path . $file_name;
        $saved_orignal = $this->imageFile->saveAs($orignal_file_full_path);
        Image::thumbnail($orignal_file_full_path, 1100, 190)->save($image_save_path . $file_name);

        if ($saved_orignal) {
            return $file_name;
        }

        return False;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDiscountcouponCategories()
    {
        return $this->hasMany(DiscountcouponCategory::className(), ['discount_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDiscountcouponDeals()
    {
        return $this->hasMany(DiscountcouponDeal::className(), ['discount_id' => 'id']);
    }

    public function getCart()
    {
        return $this->hasMany(Cart::className(), ['discountcoupon_id' => 'id']);
    }

    public function getOrder()
    {
        return $this->hasMany(Order::className(), ['discountcoupon_id' => 'id']);
    }

    public function getBannerURL($full = True)
    {
        $file_name = $this->coupon_img;

        return \yii\helpers\Url::toRoute([((\Yii::$app->id == 'app-backend') ? ".." : "") . '/uploads/banner/' . $file_name], $full);
    }

}

backend/controllers/DiscountcouponDetailsController.php
<?php

namespace backend\controllers;

use Yii;
use backend\controllers\GenxUseAdminController;
use common\models\DiscountcouponDetails;
use common\models\DiscountcouponDetailsSearch;
use common\models\DiscountcouponCategory;
use common\models\DiscountcouponDeal;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use common\models\User;

/**
 * DiscountcouponDetailsController implements the CRUD actions for DiscountcouponDetails model.
 */
class DiscountcouponDetailsController extends GenxUseAdminController
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $parent_behavior = parent::behaviors();
        $parent_behavior['access']['rules'][] = [
            'allow' => True,
            'actions' => [],
            'roles' => [User::ROLE_ADMIN]
        ];
        return $parent_behavior;
    }

    /**
     * Lists all DiscountcouponDetails models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DiscountcouponDetailsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single DiscountcouponDetails model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new DiscountcouponDetails model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new DiscountcouponDetails();

        if ($model->load(Yii::$app->request->post())) {

            $model->imageFile = UploadedFile::getInstance($model, 'coupon_img');
            if ($model->imageFile) {
                $model->coupon_img = $model->imageFile->getBaseName();
                if ($coupon_img = $model->upload()) {
                    $model->coupon_img = $coupon_img;
                }
            }
            if (!$model->save()) {
                $this->sendErrors($model->getErrors());
            } else {
                $this->sendSuccess(['Coupon Created Successfully.']);
            }


            return $this->redirect(['index', 'id' => $model->id]);
        } else {
            $this->sendErrors($model->getErrors());
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing DiscountcouponDetails model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $model->imageFile = UploadedFile::getInstance($model, 'coupon_img');
            if ($model->imageFile) {
                $model->coupon_img = $model->imageFile->getBaseName();
                if ($coupon_img = $model->upload()) {
                    $model->coupon_img = $coupon_img;
                }
            } else {
                $model->coupon_img = $model->getOldAttribute("coupon_img");
            }
            if (!$model->save()) {
                $this->sendErrors($model->getErrors());
            }
            $this->sendSuccess(['Coupon Updated Successfully.']);
            return $this->redirect('index');
        } else {
            return $this->render('update', [
                        'model' => $model
            ]);
        }
    }

    public function actionCategoryCreate($discount_id)
    {
        // $model = $this->findModel($id);
        $model = new DiscountcouponCategory();
        $searchModel = new \common\models\DiscountcouponCategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['discount_id' => $discount_id]);

        if (Yii::$app->request->post()) {

            $categoryvalue = Yii::$app->request->post();
            if (DiscountcouponCategory::find()
                            ->andWhere(['category_id' => $categoryvalue['category']['id']])
                            ->andWhere(['discount_id' => $categoryvalue['discount-id']])
                            ->exists()) {

                $this->sendErrors(['Exist' => ['This category is already available.']]);
                //return $this->redirect(\yii\helpers\Url::toRoute(['category-create', 'id' => $categoryvalue['discount-id']]));
            } else {
                $model->category_id = $categoryvalue['category']['id'];
                $model->discount_id = $discount_id;
                if ($model->save()) {
                    $discountModel = $this->findModel($discount_id);
                    $discountModel->category = 1;
                    $discountModel->save();


                    $this->sendSuccess(['Record added successfully.']);
                    //return $this->redirect(\yii\helpers\Url::toRoute(['category-create', 'id' => $categoryvalue['discount-id']]));
                } else {
                    \common\components\GenXHelper::c($model->getErrors());
                    exit();
                }
            }
        }

        return $this->render('category-create', [
                    'model' => $model,
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider
        ]);




        //  $ccmodel=new DiscountcouponCategory();
        //\common\components\GenXHelper::c(\Yii::$app->request->post());
        //      return $this->redirect(\yii\helpers\Url::toRoute(['update', 'id' => $categoryvalue['discount-id'], 'selected_tab' => 'coupon-category']));
    }

    // category Update
    public function actionCategoryUpdate($id, $discount_id)
    {
        $model = DiscountcouponCategory::findOne($id);
        // $model = new DiscountcouponCategory();
        $searchModel = new \common\models\DiscountcouponCategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['discount_id' => $discount_id]);

        if (Yii::$app->request->post()) {

            $categoryvalue = Yii::$app->request->post();
            if (DiscountcouponCategory::find()
                            ->andWhere(['category_id' => $categoryvalue['category']['id']])
                            ->andWhere(['discount_id' => $categoryvalue['discount-id']])
                            ->exists()) {

                $this->sendErrors(['Exist' => ['Change your category.']]);
                //return $this->redirect(\yii\helpers\Url::toRoute(['category-create', 'id' => $categoryvalue['discount-id']]));
            } else {

                $model->category_id = $categoryvalue['category']['id'];
                $model->discount_id = $discount_id;
                if ($model->save()) {
                    $this->sendSuccess(['Record updated successfully.']);
                    //return $this->redirect(\yii\helpers\Url::toRoute(['category-create', 'id' => $categoryvalue['discount-id']]));
                } else {
                    \common\components\GenXHelper::c($model->getErrors());
                }
            }
        }

        return $this->render('category-create', [
                    'model' => $model,
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider
        ]);




        //  $ccmodel=new DiscountcouponCategory();
        //\common\components\GenXHelper::c(\Yii::$app->request->post());
        //return $this->redirect(\yii\helpers\Url::toRoute(['update', 'id' => $categoryvalue['discount-id'], 'selected_tab' => 'coupon-category']));
    }

    public function actionCategoryDelete($id, $discount_id, $selected_tab)
    {
        DiscountcouponCategory::findOne($id)->delete();

        $checkifexist = DiscountcouponCategory::find()->andWhere(['discount_id' => $discount_id])->exists();
        if (!$checkifexist) {
            $discountModel = $this->findModel($discount_id);
            $discountModel->category = 0;
            $discountModel->save();
        }
        $this->sendSuccess(['Record Deleted successfully.']);
        $this->redirect(\yii\helpers\Url::toRoute(['category-create', 'discount_id' => $discount_id, 'selected_tab' => $selected_tab]));
    }

    public function actionDealCreate($discount_id)
    {
        $models = new DiscountcouponDeal();
        // $model = $this->findModel($id);

        $searchModel = new \common\models\DiscountcouponDealSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['discount_id' => $discount_id]);

        if (Yii::$app->request->post()) {
            $merchant = Yii::$app->request->post();
            $merchantDeal = \common\models\Deal::find()->andWhere(['user_id' => $merchant['merchant-id']])->all();
            $merchantdetail = \common\models\User::findOne($merchant['merchant-id']);

            if (isset($merchant['dealid'])) {
                $discountdealsModel = DiscountcouponDeal::find()->andWhere(['discount_id' => $discount_id])->all();
                $getDeal = [];
                foreach ($discountdealsModel as $dealid) {
                    $getDeal[] = $dealid->deal_id;
                }

                $discountModel = $this->findModel($discount_id);
                foreach ($merchant['dealid'] as $postDeal) {
                    $model = new DiscountcouponDeal();
                    if (!in_array($postDeal, $getDeal)) {
                        $model->deal_id = $postDeal;
                        $model->discount_id = $discount_id;

backend/views/discountcoupon-details/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\DiscountcouponDetails */
/* @var $form yii\widgets\ActiveForm */
?>

  <div class="wizard-content">
            <div class="wizard-pane active">
<div class="discountcoupon-details-form">

    <?php $form = ActiveForm::begin([
                                'options' => [
                                    'enctype' => 'multipart/form-data'
                                ]
                    ]); ?>
<?php
  //  \common\components\GenXHelper::c($model);
?>
     <div class="row">
         <div class="col-xs-12 col-sm-6  col-lg-4">
                            <?= $form->field($model, 'discount_coupon')->textInput(['maxlength' => true])->label("Discount Coupon Code") ?>
                        </div>
                        <div class="col-sm-6 col-lg-8">
                            <?= $form->field($model, 'discount_title')->textInput(['maxlength' => true]) ?>
                        </div>

                    </div>
   
     
    <div class="col-xs-12 col-sm-6 col-lg-4">
                            <?= $form->field($model, 'amount_type')->dropDownList(['percentage' => '% age', 'amount' => '$ amount'], ['prompt' => 'Select Category'])->label("Select Discount Type"); ?>
                        </div>
        
        <div class="col-xs-12 col-sm-6 col-lg-4">
            
            <?= $form->field($model, 'amount_value')->textInput() ?>
            
        </div>
        
        <div class="col-xs-12 col-sm-6 col-lg-4">
            
            <?= $form->field($model, 'total_person_allow')->textInput() ?>
            
        </div>
        
  
    
    

     
    <div class="col-xs-12 col-sm-6 col-lg-4">
               <?= $form->field($model, 'min_bill')->textInput() ?>
     </div>
        
        <div class="col-xs-12 col-sm-6 col-lg-4">
            
           <?= $form->field($model, 'max_credit')->textInput() ?>
            
        </div>
        
        <div class="col-xs-12 col-sm-6 col-lg-4">
            
            <?= $form->field($model, 'total_qty')->textInput() ?>
            
        </div>
        


      <div class="row">
     
    <div class="col-xs-12 col-sm-6 col-lg-6">
        
        <?php
                            echo '<label class="control-label">Start time</label>';
                            echo yii\jui\DatePicker::widget([
                               
                                'clientOptions' => [
                                    'altField' => "#discountcoupondetails-coupon_start_dt",
                                    'altFormat' => "@",
                                    'minDate'=>'today',
                                    'onSelect' => new \yii\web\JsExpression("function(selectedDate) {
            $( '#w2' ).datepicker( 'option', 'minDate', selectedDate );}"),
                                ],
                                'options' => ['class' => 'form-control',
                                    ],
                                'value' => ($model->coupon_start_dt) ? date('M d, Y', $model->coupon_start_dt) :  date('M d, Y', time())
                            ]);
                            echo $form->field($model, 'coupon_start_dt')->hiddenInput(['value' => (time() * 1000)])->label(False);
                            ?>
        
        
              
     </div>
        
        <div class="col-xs-12 col-sm-6 col-lg-6">
            <?php
                            echo '<label class="control-label">Expire time</label>';
                            echo yii\jui\DatePicker::widget([
                                'clientOptions' => [
                                    'altField' => "#discountcoupondetails-coupon_expire_dt",
                                    'altFormat' => "@",
                                    'minDate'=>date('M d, Y', $model->coupon_start_dt),
                                   'onSelect' => new \yii\web\JsExpression("function(selectedDate) {
            $( '#w1' ).datepicker( 'option', 'maxDate', selectedDate );}"),
                                ],
                              
                                'options' => ['class' => 'form-control',
                                
                                    ],
                                'value' => ($model->coupon_expire_dt) ?  date('M d, Y', $model->coupon_expire_dt) : date('M d, Y', (time() + (60 * 60 * 24 * 7)))
                               
                            ]);
                            echo $form->field($model, 'coupon_expire_dt')->hiddenInput(['value' => (time() + (60 * 60 * 24 * 7)) * 1000])->label(False);
                            ?>
            
          
            
        </div>
        
        
        
    </div>
    
      <div class="row">
     
    <div class="col-xs-12 col-sm-6 col-lg-6">
               <?= $form->field($model, 'coupon_img')->fileInput() ?>
     </div>
        
        <div class="col-xs-12 col-sm-6 col-lg-6">
            
           <?= $form->field($model, 'coupon_img_url')->textInput() ?>
            
        </div>
        
        
    </div>



    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create Coupon' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
</div>
</div>

backend/views/discountcoupon-details/_formcategory.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\DealOption */
/* @var $form yii\widgets\ActiveForm */
?>
<!-- Panel Wizard Form -->
<h4>
   
</h4>
<div class="panel">
    <div class="panel-body">
        <!-- Steps -->
       
        <!-- End Steps -->

        <!-- Wizard Content -->
        <div class="wizard-content">
            <div class="wizard-pane active">
                <div class="deal-option-form">
                    <div class="row">
                        <?php $form = ActiveForm::begin(); ?>
                        <div class="col-lg-12">
                            
                 Search Category
                  <?php 
                
                     echo yii\jui\AutoComplete::widget([
                         'value'=>($model->category_id) ? $model->category->name : "",   
                         'clientOptions' => [
                                'source' => Url::toRoute(['/category/autocomplete']),
                               
                                'select' => new yii\web\JsExpression('function( event, ui ) {
                            
                            $("#user-id").val(ui.item.id);
                            
                            
                            
                          }'),
                            ],
                            'options' => ['class' => 'form-control']
                        ]);
                     ?>
                 <input type="hidden" name="category[id]" id="user-id" value="<?= ($model->category_id)? $model->category_id : "" ?>">
              
                            
                       
                        </div>
                         
                        <div class="col-lg-12"><br>
                            <?php
                            if(isset($_REQUEST['update_id'])){?>
                            <input type="hidden" name="update_id" value="1">
                            <?php }?>
                        
                        <div class="form-group pull-right">
                            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                        </div>
                            <input type="hidden" name="discount-id" value="<?= $discount_id; ?>">   
                        </div>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
        <!-- End Wizard Content -->

    </div>
</div>

backend/views/discountcoupon-details/_formdeal.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\DealOption */
/* @var $form yii\widgets\ActiveForm */
?>
<!-- Panel Wizard Form -->
<h4>
   
</h4>
<div class="panel">
    <div class="panel-body">
        <!-- Steps -->
       
        <!-- End Steps -->

        <!-- Wizard Content -->
        <div class="wizard-content">
            <div class="wizard-pane active">
                <div class="deal-option-form">
                     <form action="<?php echo yii\helpers\Url::toRoute(['deal-create', 'id' => $model->id, 'discount_id' => $discount_id,'selected_tab'=>$_REQUEST['selected_tab']]) ?>" method="POST">
                       
                    <div class="row">
                            <?php
                                            $request = Yii::$app->getRequest();
                                            echo yii\helpers\Html::hiddenInput($request->csrfParam, $request->getCsrfToken());
                   ?>  
                        <div class="col-lg-12">
                            
                 Search Merchant
                  <?php 
                
                     echo yii\jui\AutoComplete::widget([
                            'value'=>($merchant_detail) ? $merchant_detail->name : "",
                            'clientOptions' => [
                                'source' => Url::toRoute(['/merchant/merchant-autocomplete']),
                                'select' => new yii\web\JsExpression('function( event, ui ) {
                            $("#merchant").val(ui.item.id);
                            
                            
                          }'),
                            ],
                            'options' => ['class' => 'form-control']
                        ]);
                     ?>
                 <input type="hidden" name="merchant-id" id="merchant" value="<?= ($merchant_detail) ? $merchant_detail->id : "" ?>">
                       
                        </div>
                        
                         
                        <div class="col-lg-12">
                            <?php
                            if($merchant_deal){
                                foreach ($merchant_deal as $deal){
                                ?>
                            <div class="col-lg-12">
                                <br>
                                <input type="checkbox" name="dealid[]" value="<?= $deal->id; ?>"> <?= $deal->title; ?>
                                <br>
                            </div>
                            <?php
                             }
                            }
                            ?>
                            <br>
                            <?php
                            if(isset($_REQUEST['update_id'])){?>
                            <input type="hidden" name="update_id" value="1">
                            <?php }?>
                        
                        <div class="form-group pull-right">
                            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                        </div>
                            <input type="hidden" name="discount-id" value="<?= $discount_id; ?>">   
                        </div>
                    </div>
            </form>
                </div>
            </div>
        </div>
        <!-- End Wizard Content -->

    </div>
</div>

backend/views/discountcoupon-details/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\DiscountcouponDetailsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="discountcoupon-details-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'discount_coupon') ?>

    <?= $form->field($model, 'discount_title') ?>

    <?= $form->field($model, 'amount_type') ?>

    <?= $form->field($model, 'amount_value') ?>

    <?php // echo $form->field($model, 'total_person_allow') ?>

    <?php // echo $form->field($model, 'min_bill') ?>

    <?php // echo $form->field($model, 'max_credit') ?>

    <?php // echo $form->field($model, 'coupon_start_dt') ?>

    <?php // echo $form->field($model, 'coupon_expire_dt') ?>

    <?php // echo $form->field($model, 'total_qty') ?>

    <?php // echo $form->field($model, 'total_used') ?>

    <?php // echo $form->field($model, 'category') ?>

    <?php // echo $form->field($model, 'deal') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/discountcoupon-details/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\components\GenXHelper;
use yii\helpers\Url;
use common\components\GenxGridHelper;



/* @var $this yii\web\View */
/* @var $searchModel common\models\DiscountcouponDetailsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Discountcoupon Details';
$this->params['breadcrumbs'][] = $this->title;
GenXHelper::contentHeader($this);
GenXHelper::contentHeaderButtons($this, [
    [
        "title" => "New",
        "url" => Url::toRoute(['/discountcoupon-details/create']),
        "icon" => "fa fa-plus",
    ],
    [
        "title" => "Refresh",
        "url" => Url::toRoute(['/discountcoupon-details']),
        "icon" => "fa fa-refresh",
    ],
]);
?>
<div class="discountcoupon-details-index">
    <div class="table-responsive">
    
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

   
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                     
                    'attribute' => 'Id',
                    'format'=>'raw',
                    'value' => function($model) {
                        return $model->id;
                          
                    },
                    
                ],  
            'discount_coupon',
            'discount_title',
            'amount_type',
            [
                     
                    'attribute' => 'Amount Value',
                    'format'=>'raw',
                    'value' => function($model) {
                        return $model->amount_value;
                          
                    },
                    
                ],  
            [
                     
                    'attribute' => 'Allow Category',
                    'format'=>'raw',
                    'value' => function($model) {
                        $total_cat = $model->getDiscountcouponCategories()->count();
                        return $total_cat;
                          
                    },
                    
                ],
                [
                     
                    'attribute' => 'Allow Deals',
                    'format'=>'raw',
                    'value' => function($model) {
                        $total_deal = $model->getDiscountcouponDeals()->count();
                        return $total_deal;
                          
                    },
                    
                ],
            // 'total_person_allow',
            // 'min_bill',
            // 'max_credit',
            // 'coupon_start_dt',
            // 'coupon_expire_dt',
            // 'total_qty',
            // 'total_used',
            // 'category',
            // 'deal',
            // 'status',
            // 'created_at',
            // 'updated_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>
</div>